In [2]:
import numpy as np

In [4]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# np.array()로 생성한 객체는 numpy.ndarray이다. list가 아니다
type(ar)

numpy.ndarray

In [6]:
# (10,) -> 1차원의 10칸 갖는  ndarray
ar.shape

(10,)

In [8]:
x = np.array([1,2,3,4,5])
x**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [10]:
x = np.array([1,2,3,4,5])
x*2

array([ 2,  4,  6,  8, 10])

In [12]:
c = np.array([[1,2,3],
            [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c.shape

(2, 3)

In [14]:
# 행의 갯수
len(c)

2

In [17]:
# 열의 개수
len(c[1])

3

In [18]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [60]:
b = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
               [[13,14,15,16],
                [1,2,3,4],
                [5,6,7,8]]])
b.T

array([[[ 1, 13],
        [ 5,  1],
        [ 9,  5]],

       [[ 2, 14],
        [ 6,  2],
        [10,  6]],

       [[ 3, 15],
        [ 7,  3],
        [11,  7]],

       [[ 4, 16],
        [ 8,  4],
        [12,  8]]])

In [61]:
b = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
               [[13,14,15,16],
                [1,2,3,4],
                [5,6,7,8]]])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

In [21]:
test = [[1,2,3,4],[5,6,7,8]]
test

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a[:,1]


array([2, 6])

In [28]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
# 7
m[1,2]
# 14
m[2,4]
# [6,7]
m[1,1:3]
# [7,12]
m[1:3,2]
# [[3,4],[8,9]]
m[:2,3:5]

array([[3, 4],
       [8, 9]])

In [33]:
a = np.zeros((5,2), dtype = 'i')
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [44]:
d = np.zeros(5, dtype = 'i8')
d

array([0, 0, 0, 0, 0], dtype=int64)

In [64]:
d = np.zeros((4,5,3), dtype = 'i8')
d.T

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [54]:
# 틀만 만드는 느낌
g = np.empty((2,3,4))
g

array([[[9.05484484e-312, 7.85564377e-322, 0.00000000e+000,
         0.00000000e+000],
        [1.33511018e-306, 1.15998412e-028, 4.31603868e-080,
         1.94919985e-153],
        [1.35717430e+131, 1.03080325e+136, 6.01347002e-154,
         1.03080325e+136]],

       [[6.01347002e-154, 1.03080325e+136, 6.01347002e-154,
         1.03080325e+136],
        [6.01347002e-154, 5.49891270e-095, 8.78959876e+198,
         2.18229348e-094],
        [1.43267083e+161, 2.20832505e-094, 9.80058441e+252,
         1.23971686e+224]]])

In [59]:
a =np.linspace(0,100,5)
a

array([  0.,  25.,  50.,  75., 100.])

In [71]:
a = np.arange(10)
b = a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
# -1은 '니가 알아서 잘 해라'라는 뜻
a = np.arange(12)
b = a.reshape(3,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.array([0,0,0,1,1],[0,0,0,1,1],[0,0,0,1,1],[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150])
np.tile(a,2)

In [102]:
zeros = np.zeros((3,3))
ones = np.ones((3,2))
tens = np.linspace(10,150,15)
reshaped_tens = tens.reshape(3,-1)

a = np.hstack([zeros,ones])
b = np.vstack([a,reshaped_tens])
c = np.tile(b,(2,1))

c

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [115]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                    [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                    [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                    [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                    [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

practice.max()
practice.sum(axis=0)
practice.max(axis=0)
practice.mean(axis=1)
practice.min(axis=1)

array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ])

In [117]:
scores = np.array([[1, 2, 3, 4],
                  [46, 99, 100, 71],
                  [81, 59, 90, 100]])

scores.sort(axis=1)
scores

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [117]:
scores = np.array([[1, 2, 3, 4],
                  [46, 99, 100, 71],
                  [81, 59, 90, 100]])

print(scores[],[])

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [121]:
np.random.seed(0)

In [123]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [245]:
np.random.rand(10)

array([0.24456961, 0.45821226, 0.75740656, 0.20362093, 0.56631161,
       0.18581675, 0.10473611, 0.11655861, 0.35763903, 0.00465484])

In [246]:
np.random.seed(0)
np.random.randint(0,2,100)

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [252]:
np.random.seed(0)
a = np.random.choice(2,100)
np.mean(a)

0.56

In [251]:
np.mean(a)

0.4