In [1]:
import numpy as np

In [3]:
np.random.seed(0)
result = np.random.randint(1,7,100)
np.mean(result)

3.42

In [7]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8,9],
              [10,11,12]])

c = a+b
c

array([[ 8, 10, 12],
       [14, 16, 18]])

In [8]:
a = np.array(([1,2,3],[4,5,6]))
b = np.array(([7,8,9],[10,11,12]))
a = a * 2
b = b * 2
a = a[1,:]
b = b[0,:]
c = np.vstack([a,b])
print(c)

[[ 8 10 12]
 [14 16 18]]


In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])

a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [12]:
a = np.arange(1,10)
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [20]:
a = np.ones([2,3])
b = np.zeros([2,3])
c = np.ones([2,3])

np.dstack([a,b,c])

array([[[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]],

       [[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]]])

In [17]:
a = np.arange(50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
# dstack연습

a = np.ones((4,2))
b = np.zeros((4,2))
c = np.array([['a','b'],['c','d'],['e','f'],['g','h']])
print(a.shape)
print(a)
print()
print(b)
print()
print(c)
d = np.stack([a,b,c], axis=2)
d.shape
print(d)

In [25]:
a = np.zeros((3,3,3), dtype='U10')
a

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [27]:
array4 = np.array([[['','','']]*3]*3, dtype='<U10')
array4

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [ ]:
메롱 메롱 메롱 메롱 마우스 신기방귀

In [31]:
a = np.array([[['playdata']*3]*3]*3)
a

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [33]:
np.full((3,3,3),'playdata', dtype='U8')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [35]:
a = np.arange(2,41,2).reshape(2,2,5)
a

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [37]:
np.eye(4, dtype='i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [39]:
a = np.ones((2,3,2)).astype('i')
a

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [46]:
np.random.seed(0)
result = np.random.randint(0,2,9).astype('?').reshape(3,3)
result

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [52]:
np.random.seed(0)
a = np.random.rand(10)
(a*10).astype('i')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [64]:
a = np.ones((10,10)).astype('i')
n = range(1,9)
a[n,1:-1] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [87]:
a = np.ones((10,10)).astype('i')
a[0] = 0
a[-1] = 0
a[:,0] = 0
a[:,9] = 0

print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [101]:
a = np.ones((8,8))
for n in range(8): 
    a[n][n]=0
n += 1 
n=0
print(a)

[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0.]]


In [120]:
a = np.ones((8,8))
a[0::2,1::2]=0
a[1::2,0::2]=0

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [126]:
a = np.array([[1,0]*4,[0,1]*4]*4)
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [127]:
a = np.tile(np.eye(2),(4,4))
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [141]:
a = np.arange(11)
a[4:7] = [-4,-5,-6]
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [150]:
a = np.arange(3,101,3)
b = sum(a)
b

1683

In [152]:
np.arange(3,101,3).sum()

1683

In [153]:
np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [171]:
a = int(input("입력한 숫자만큼 로또 번호를 생성해드립니다."))
n = range(46)
np.random.seed(0)    
result = np.random.choice(1,45,6)
print(n)

입력한 숫자만큼 로또 번호를 생성해드립니다. 4


range(1, 46)


In [ ]:
while True:
    n = input("자연수를 입력해주세요.")
    try:
        for i in range(int(n)):
            k = np.array([np.random.choice(np.arange(1, 46), replace=False) for _ in range(6)])
            print(np.sort(k))
        break;
    except ValueError:
        print("자연수를 입력해주세요.")

In [ ]:
while True:
    try:
        count = int(input("로또 몇 개?"))
        if count <= 0:
            raise Error
        

In [176]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])
(resp_time>200).sum()

8

In [184]:
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])

a = np.percentile(resp_time,0)
b = np.percentile(resp_time, 25)
c = np.median(resp_time)
d = np.percentile(resp_time, 75)
e = np.percentile(resp_time, 100)

result(f"최소값:{a} 1사분위:{b} 2사분위:{c} 3사분위:{d} 최대값:{e}")
print(result)

TypeError: 'numpy.ndarray' object is not callable

In [190]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])

p, count = np.unique(result, return_counts=True)


array([81, 53, 66], dtype=int64)