In [ ]:
<a href="https://colab.research.google.com/github/HyeshinLim/pythonbasic/blob/main/practice_review_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2023-02-17 1주차 Day 4 내용 복습

In [ ]:
# 공무원 시험 결과가 국어, 영어, 한국사, 선택 교과1, 선택 교과2의 점수가 리스트 형태로
# 제공됩니다. 이때 한 과목이라도 60점 미만이면 과락입니다. 과락이면 False를 과락이
# 아니면 True를 출력하도록 코드를 완성해보세요.

## [국어, 영어, 한국사, 선택 교과1, 선택 교과2]
##scores = [88, 73, 89, 59, 77]
##????? 

#if문으로만 문제풀기

scores = [88,73,89,59,77]

if scores[0] < 60:
    print("False")
elif scores[1] < 60:
    print("False")
elif scores[2] < 60:
    print("False")
elif scores[3] < 60:
    print("False")
elif scores[4] < 60:
    print("False")
else:
    print("True")

False


In [ ]:
# 공무원 시험 결과가 국어, 영어, 한국사, 선택 교과1, 선택 교과2의 점수가 리스트 형태로
# 제공됩니다. 이때 한 과목이라도 60점 미만이면 과락입니다. 과락이면 False를 과락이
# 아니면 True를 출력하도록 코드를 완성해보세요.

## [국어, 영어, 한국사, 선택 교과1, 선택 교과2]
##scores = [88, 73, 89, 59, 77]
##????? 

#for문으로 문제풀기

scores = [88,73,89,59,77]

for i in scores:
    if i<60:
        print("False")
    else:
        print("True")
       

True
True
True
False
True


In [ ]:
n = int(input("숫자를 입력하세요:"))
for i in range(n,0,-1):
    for j in range(i):
        print(i, end="\t")
    print()

숫자를 입력하세요: 4


4	4	4	4	
3	3	3	
2	2	
1	


In [ ]:
for i in range(10):
    if i==0 or i==9:
        print("* "*10)
    else:
        print("*                 *")

* * * * * * * * * * 
*                 *
*                 *
*                 *
*                 *
*                 *
*                 *
*                 *
*                 *
* * * * * * * * * * 


# 2023-02-18 1주차 내용 복습 1

In [ ]:
# 문자열 리터럴 - raw string

a = r'asdf\trr'
b = 'asdf\trr'

print(a)
print(b)

asdf\trr
asdf	rr


In [ ]:
# 문자열 리터러러 - \ (역슬래쉬)

a = """\
안녕
"""

print(a)

안녕



In [4]:
# 리스트의 값 변경하기

name = ['하람', '혜신', '하유']
print(name)

name[2] = '하윤'

print(name)

['하람', '혜신', '하유']
['하람', '혜신', '하윤']


In [12]:
# 리스트 더하기
name = ['하람', '혜신', '하윤']
name.append('영주')
print(name)

['하람', '혜신', '하윤', '영주']


In [ ]:
# 리스트 안에 리스트

girl = ['하람','혜신','하윤']
boy = ['석진','정훈','준하']

# '+'를 쓰면 리스트를 하나로 합친다. 그래서 리스트 'friends'는 요소가 한 개다.
friends = [girl+boy]
print(friends)

# ','를 쓰면 추가된다. 그래서 리스트 'friends'는 요소가 두 개다.
friends = [girl,boy]
print(friends)

# 리스트 'friends' 인덱스0(첫번째 요소) 안에 인덱스0(첫번째 요소)를 출력하는 코드 
print(friends[0][0])

[['하람', '혜신', '하윤', '석진', '정훈', '준하']]
[['하람', '혜신', '하윤'], ['석진', '정훈', '준하']]
하람


In [ ]:
# 리스트 요소 '찾기' 기능

my_army_friends = ['석진','정훈','재욱','민성']
print('준하' in my_army_friends)
print('재욱' in my_army_friends)

False
True


In [ ]:
# 리스트 매서드

numbers = [1,2,3,4,5]

# 맨 뒤에 요소 추가하기
numbers.append(6)
print("1.",numbers)

# 인덱스에 요소 추가하기
numbers.insert(3,2)
numbers.insert(len(numbers),"last")
print("2.",numbers)

# 요소 추가하기(연장하기) 근데 대괄호를 써줘야 한다.
# 'int' object is not iterable
# extend() takes exactly one argument
numbers.extend([7, 8])

print("3.",numbers)

numbers.pop()
print("4.",numbers)

1. [1, 2, 3, 4, 5, 6]
2. [1, 2, 3, 2, 4, 5, 6, 'last']
3. [1, 2, 3, 2, 4, 5, 6, 'last', 7, 8]
4. [1, 2, 3, 2, 4, 5, 6, 'last', 7]


In [ ]:
# 튜플
# 튜플은 소괄호 생략 가능하다

Im_Tupple = '난','튜','플'
print(Im_Tupple)

Im_Tupple_too = ('나','도','튜','플')
print(Im_Tupple_too)

('난', '튜', '플')
('나', '도', '튜', '플')


In [ ]:
#Unpacking

# 튜플(소괄호를 생략한)을 언팩킹
flavor1, flavor2 = '바닐라','레몬'
print(flavor1,flavor2)

# 리스트를 언팩킹
flavor3, flavor4 = ['다크초코','피스타치오']
print(flavor3,flavor4)

one,two,three,four = "블루베리"
print(one,two,three,four)


바닐라 레몬
다크초코 피스타치오
블 루 베 리


In [ ]:
for _ in ("파 도 솔"):
  print(_,end=",")

파, ,도, ,솔,

In [ ]:
# .reverse() 와 reversed()의 차이
# .reverse()는 리스트 매소드이고 괄호 안에 아무것도 넣지 않는다. 출력은 하지 않고 거꾸로 섞는 것까지만 해서 따로 또 'print(변수)'를 해야 한다.
# reversed()는 print(list(reversed(변수))) 이렇게 사용한다.

alph = ["a", "b", "c", "d"]
print(list(reversed(alph)))
# ['d', 'c', 'b', 'a']

alph = ["a", "b", "c", "d"]
alph.reverse()
print(alph)
# ['d', 'c', 'b', 'a']

['d', 'c', 'b', 'a']
['d', 'c', 'b', 'a']


In [ ]:
# while loop
# while문 순서
# 1. 초기식
# 2. while 조건식
# 3. 반복할 코드
# 4. 변화식

i = 0
while i < 10:
  print(":)")
  i += 1
# "i가 9일 때까지만 반복해서 :)을 찍어줄게."

:)
:)
:)
:)
:)
:)
:)
:)
:)
:)


# 2023-02-19 1주차 내용 복습 2

In [ ]:
# break
# break는 보통 if문과 함께 쓰인다.

# while loop + break
i = 0
while True:
  print('Hi', end='\t')
  i += 1
  if i == 10:
    break

# for loop + break
for _ in range(1000):
  print('_', end='\t')
  if _ == 10:
    break

Hi	Hi	Hi	Hi	Hi	Hi	Hi	Hi	Hi	Hi	_	_	_	_	_	_	_	_	_	_	_	

In [17]:
# dictionary
# dict()함수 예시

dict([(1,2)])
#{1: 2}
dict([('과자','프링글스')])
#{'과자': '프링글스'}
icecream = dict(아이스크림='바닐라',아이스크림2='초코',아이스크림3='딸기')
#{'아이스크림': '바닐라', '아이스크림2': '초코', '아이스크림3': '딸기'}
print(icecream['아이스크림2'])
# 초코

초코


# 2023-02-20 2주차 Day 6 내용 복습

In [ ]:
# 리스트 안에 있는 리스트는 같은 주소 값을 갖는다.

# 2023-02-20 1주차 수업 예제문제 풀기

In [4]:
# 문자열을 변경하고 싶을 때

sentence = "오늘도 파이팅!"
print(sentence)

new_sentence = "내일도" + sentence[3::]
print(new_sentence)

오늘도 파이팅!
내일도 파이팅!


In [24]:
# list 생성하기

a = [1,2,3,4,5,6]
print(a)

b = list('123456')
print(b)
b[0] = '2'
print(b)

[1, 2, 3, 4, 5, 6]
['1', '2', '3', '4', '5', '6']
['2', '2', '3', '4', '5', '6']


In [29]:
# 60점 미만이 있으면 fail 출력하게 만들기
scores = [80,65,59,77]
for i in range(len(scores)):
    if scores[i]<60:
        print("fail")
    else:
        print("success")

success
success
fail
success


In [32]:
# 평균이 60점 미만이 있으면 "탈락" 출력하게 만들기
scores = [80,65,59,77]
total =0

for i in range(len(scores)):
    total += scores[i]
avg=total/len(scores)

if avg <60:
    print("탈락")
else:
    print("합격")
print(avg)      

합격
70.25


In [25]:
# 이용자에게 받은 정수 4개 중에 60 미만이 있으면 "탈락" 출력하게 만들기
scores = list((input("정수 4개를 입력하세요")).split( ))
scores = list(map(int, scores))

i = 0
while i < len(scores):
    if scores[i] > 60:
        print("합격")
    else:
        print("탈락")        
    i+=1

정수 4개를 입력하세요 56 56 56 56


탈락입니다
탈락입니다
탈락입니다
탈락입니다


In [35]:
sentence = "지금 시각은 {}시 {}분 입니다.".format('오후 8', '오')
print(sentence)

지금 시각은 오후 8시 오분 입니다.


In [4]:
print(f"지금은 {'ojj'}시 {'os'}분 입니다.")

지금은 ojj시 os분 입니다.


In [7]:
a=2
if a == 2:
    print(a)
print(3)

2
3


# 2023-03-02 3주차 Day 12 내용 복습

In [3]:
import numpy as np

a = np.array([1,2,3,4])
a*2

array([2, 4, 6, 8])

In [7]:
a = np.array([5,2,4])
b = np.array([3,5,8])

a <= b

array([False,  True,  True])

In [14]:
a = np.array([[5,6,8],[15,2,3]])
a
# array([[ 5,  6,  8],
#       [15,  2,  3]])

# 행 갯수
len(a)
# 열 갯수
len(a[0])

array([[ 5,  6,  8],
       [15,  2,  3]])

In [19]:
# 3차원 배열 구조
# 깊이 * 행 * 열
# depth * row * column
# axis0 * axis1 * axis2

# 4*3*2
a = np.array([[[1,2],
              [3,4],
              [5,6]],
             [[7,8],
             [9,10],
             [11,12]],
             [[13,14],
              [15,16],
              [17,18]],
             [[19,20],
             [21,22],
             [23,24]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [21]:
# 3차원 배열 구조
# 깊이 * 행 * 열
# depth * row * column
# axis0 * axis1 * axis2

# 4*3*2
a = np.array([[[1,2],
              [3,4],
              [5,6]],
             [[7,8],
             [9,10],
             [11,12]],
             [[13,14],
              [15,16],
              [17,18]],
             [[19,20],
             [21,22],
             [23,24]]])
a.reshape(2,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [21]:
# 3차원 배열 구조
# 깊이 * 행 * 열
# depth * row * column
# axis0 * axis1 * axis2

# 4*3*2
a = np.array([[[1,2],
              [3,4],
              [5,6]],
             [[7,8],
             [9,10],
             [11,12]],
             [[13,14],
              [15,16],
              [17,18]],
             [[19,20],
             [21,22],
             [23,24]]])
a.reshape(2,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [35]:
a = np.array([[0,1,2,3,4],
            [5,6,7,8,9],
             [10,11,12,13,14]])
a[:2,3:]


array([[3, 4],
       [8, 9]])

In [46]:
a = np.arange(24)

a.reshape(3,4,-1)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
a = np.ones([2,3])
b = np.zeros([5,3])

c = np.vstack([a,b])
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
a = np.ones([5,2])
b = np.zeros([5,1])

c = np.hstack([b,a])
c

array([[0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.]])

# 2023-03-05 3주차 내용 복습

In [1]:
import numpy as np

In [11]:
a = np.zeros((3,2), dtype='i')
b = np.ones_like(a)
b

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
a = np.zeros((4,3))
b = np.ones((4,3))

np.dstack([a,b])

In [18]:
a = np.zeros((4,3))
b = np.ones((4,3))

np.stack([a,b])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
a = np.zeros((4,3))
b = np.ones((4,3))

c = np.stack([a,b], axis=2)
c.shape
c

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [26]:
a = np.array([[1,2,3],
             [4,5,6]])
np.tile(a,(3,2,3))

array([[[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]],

       [[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]],

       [[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]]])

In [41]:
a = a.reshape((2,3))
a.sum(axis=1)

array([ 6, 15])

# 2023-03-06 4주차 Day 14 내용 복습

In [1]:
import pandas as pd

In [9]:
a = pd.Series(range(10,16))
print("12보다 큰 수 갯수:",sum(a>12))
print(a)

12보다 큰 수 갯수: 3
0    10
1    11
2    12
3    13
4    14
5    15
dtype: int64


In [16]:
a.name = '10~15'
a

0    10
1    11
2    12
3    13
4    14
5    15
Name: 10~15, dtype: int64

In [18]:
d = {'a':1,'b':2, 'c':3}
series = pd.Series(d, ['c','a','b'])
series

c    3
a    1
b    2
dtype: int64

In [ ]:
# ------Series를 만드는 방법------
##1
# pd.Series([데이터],[인덱스])

##2
# a={'a':1,'b':2}
pd.Series(a)

##3
pd.Series({'a':1,'b':2})

# ------Series Slicing------
##1
a = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
a = pd.Series(a)
a['a':'b']

In [51]:
a1 = pd.Series([12035,95264,61348,84847],
              ['가','나','다','마'])
a2 = pd.Series({'가':25134,'나':56829,'다':12354,'라':56812})
b = a1-a2
b[b.notnull()]

가   -13099.0
나    38435.0
다    48994.0
dtype: float64

In [60]:
c=a2-a1
c[c.notnull()]
c[[c.values.argmax()]]

라   NaN
dtype: float64

In [ ]:
a1['라'] = 68451
del a1['다']

In [74]:
a1

가    12035
마    84847
라    68451
dtype: int64

In [78]:
data = {
    '09:00':[11,10,10],
    '15:00':[18,18,16],
    '18:00':[15,16,14],
    '12:00':[15,16,14]
}
columns = ['09:00','12:00','15:00','18:00']
index = ['집','교회','학원']

df = pd.DataFrame(data,index,columns)
df.columns.name = '시간대'
df.index.name = '장소'

df

시간대  09:00  12:00  15:00  18:00
장소                             
집       11     15     18     15
교회      10     16     18     16
학원      10     14     16     14

In [79]:
data = {
    '09:00':[11,10,10],
    '15:00':[18,18,16],
    '18:00':[15,16,14],
    '12:00':[15,16,14]
}
columns = ['09:00','12:00','15:00','18:00']
index = ['집','교회','학원']

df = pd.DataFrame(data,index,columns)
df.columns.name = '시간대'
df.index.name = '장소'

df.T

장소      집  교회  학원
시간대              
09:00  11  10  10
12:00  15  16  14
15:00  18  18  16
18:00  15  16  14

In [103]:
data = {
    '09:00':[11,10,10],
    '15:00':[18,18,16],
    '18:00':[15,16,14],
    '12:00':[15,16,14]
}
columns = ['09:00','12:00','15:00','18:00']
index = ['집','교회','학원']

df = pd.DataFrame(data,index,columns)
df.columns.name = '시간대'
df.index.name = '장소'
df=df.T
df['월비'] = (df['집']+4)
df['집']['12:00']

15

In [99]:
import numpy as np
pd.DataFrame(np.arange(24).reshape(3,-1))

0   1   2   3   4   5   6   7
0   0   1   2   3   4   5   6   7
1   8   9  10  11  12  13  14  15
2  16  17  18  19  20  21  22  23

In [104]:
np.unique(['민초','민초','녹차','바닐라','초코','초코','딸기'])

array(['녹차', '딸기', '민초', '바닐라', '초코'], dtype='<U3')

In [107]:
ice_cream = np.array(['민초','민초','녹차','바닐라','초코','초코','딸기'])
flavor, count = np.unique(ice_cream, return_counts=True)

In [115]:
count.sort()
print(count,
flavor)

[1 1 1 2 2] ['녹차' '딸기' '민초' '바닐라' '초코']


In [116]:
np.bincount([0,1,1,2,3,5,7], minlength=7)

array([1, 2, 1, 1, 0, 1, 0, 1], dtype=int64)

In [126]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [140]:
# 
a = np.arange(4)
b = np.array([2], dtype='f')
c = a * b
print(a)
print(b)
print(c)
print(type(c))

a==c

[0 1 2 3]
[2.]
[0. 2. 4. 6.]
<class 'numpy.ndarray'>


array([ True, False, False, False])

In [ ]:
# df[인덱싱]은 column
# df[:슬라이싱]은 row